output-format: text

strictness: medium
test-warnings: true
doc-warnings: false

ignore-paths:
  - .cache
  - .mypy_cache
  - .pytest_cache
  - .tox
  - build
  - dist
  - lispcore.py
  - tests

pep8:
  disable:
    - E741
  options:
    max-line-length: 120

pyflakes:
  disable:
    - F821

pylint:
  disable:
    - import-outside-toplevel
    - len-as-condition
    - logging-format-interpolation
    - logging-fstring-interpolation
    - no-else-continue
    - no-else-raise
    - no-else-return
    - protected-access
    - unsubscriptable-object
    - useless-import-alias
